# Generated by Django 2.2.7 on 2019-12-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='is_recomment',
            new_name='is_recommend',
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='course.Course', verbose_name='课程名称'),
        ),
    ]
