# Generated by Django 2.2.7 on 2019-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courseexpire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexpire',
            options={'verbose_name': '课程有效期', 'verbose_name_plural': '课程有效期'},
        ),
        migrations.AlterField(
            model_name='courseexpire',
            name='expire_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='提示文本'),
        ),
        migrations.AlterField(
            model_name='courseexpire',
            name='expire_time',
            field=models.IntegerField(blank=True, help_text='有效期按天数计算', null=True, verbose_name='有效期'),
        ),
    ]
