# Generated by Django 2.2.7 on 2019-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='广告标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='广告图片')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='广告链接')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否是站外链接')),
                ('remark', models.TextField(verbose_name='备注信息')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
