# Generated by Django 2.2.7 on 2019-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='position',
            field=models.IntegerField(choices=[(1, '顶部导航'), (2, '脚部导航')], default=1, verbose_name='导航位置'),
        ),
    ]
