# Generated by Django 2.2.7 on 2019-11-25 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191125_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播广告', 'verbose_name_plural': '轮播广告'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_http',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='banner', verbose_name='广告图片'),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(default=1, max_length=500, verbose_name='广告链接'),
            preserve_default=False,
        ),
    ]
