# Generated by Django 2.2.7 on 2019-11-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191125_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='is_http',
            field=models.BooleanField(default=False, verbose_name='是否是站外地址'),
        ),
    ]
