# Generated by Django 2.2.7 on 2019-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '已支付'), (2, '已取消'), (0, '未支付'), (3, '超时取消')], default=0, verbose_name='订单状态'),
        ),
    ]
