# Generated by Django 2.2.7 on 2019-12-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191208_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.SmallIntegerField(choices=[(1, '已支付'), (0, '未支付'), (3, '超时取消'), (2, '已取消')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信支付')], default=1, verbose_name='支付方式'),
        ),
    ]
